name: Deploy and Restart Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - name: Publish project
        run: dotnet publish backend/backend.csproj -c Release -o publish

      - name: Move project to target directory
        run: |
          TARGET_DIR="/var/www/innoviahub/backend"
          cp -r ./publish/ "$TARGET_DIR"

      - name: Move frontend project to target directory
        run: |
          TARGET_DIR="/var/www/innoviahub/frontend"
          cp -r frontend/* "$TARGET_DIR"
          cd "$TARGET_DIR" && sudo npm install

      - name: Restart innoviahub.service
        run: |
          sudo systemctl restart innoviahub.service

      - name: Restart innoviahub-frontend.service
        run: |
          sudo systemctl restart innoviahub-frontend.service
