name: Deploy and Restart Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Move project to target directory
        run: |
          TARGET_DIR="/var/www/innoviahub/backend/publish"
          cp -r ./backend/* "$TARGET_DIR"

      - name: Restart innoviahub.service
        run: |
          sudo systemctl restart innoviahub.service
