name: Deploy and Restart Service

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build & publish
        run: |
          dotnet publish backend/backend.csproj -c Release -o ./artifacts/publish
          ls -la ./artifacts/publish

      - name: Sync to server (preserve .env)
        run: |
          TARGET_BASE="/var/www/innoviahub/backend-tintin"
          TARGET_DIR="$TARGET_BASE/publish"


          sudo mkdir -p "$TARGET_DIR"


          sudo rsync -a --delete --exclude '.env' ./artifacts/publish/ "$TARGET_DIR/"

          sudo chown -R Hub3:Hub3 "$TARGET_BASE"
          sudo find "$TARGET_DIR" -type f -exec chmod 640 {} \;
          sudo find "$TARGET_DIR" -type d -exec chmod 750 {} \;

      - name: Restart service
        run: |
          sudo systemctl restart innoviahub-tintin
          sudo systemctl status innoviahub-tintin --no-pager -n 30
